services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: payment_checkout
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: